server:
  tomcat:
    accesslog:
      directory: /yazuo/logs/${spring.application.name}/tomcat_log
      request-attributes-enabled: true
      enabled: true

logging:
  path: /yazuo/logs/${spring.application.name}
  file: ${logging.path}/info.log
  config: classpath:logback-spring.xml
      